name: Deploy the best website of the entire Internet

on:
  push:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Node dependencies
              run: cd Veel-Glorie && npm install

            - name: Build
              run: cd Veel-Glorie && npm run build

            - name: Get ready to deploy
              run: cp -r ./Veel-Glorie/dist .

            # - name: Deploy
            #   uses: stefanzweifel/git-auto-commit-action@v4

            - name: Commit report
              run: |
                git config --global user.name "Veel-Glorie BOT"
                git config --global user.email "veel-glorie@users.noreply.github.com"
                git commit -am "Automated report"
                git push
