name: Deploy the best website of the entire Internet

on:
  push:

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Node dependencies
              run: |
                cd Veel-Glorie
                npm install

            - name: Remove previous version
              run: rm -rf assets

            - name: Build
              run: |
                cd Veel-Glorie
                npm run build

            - name: Get ready to deploy
              run: |
                cp -r ./Veel-Glorie/dist/* .
                cp ./Veel-Glorie/src/favicon.ico .
                cp ./Veel-Glorie/src/manifest.json .
                cp ./Veel-Glorie/src/robots.txt .
                cp ./Veel-Glorie/src/sitemap.xml .
                cp ./Veel-Glorie/src/sw.js .

            - name: Deploy
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: "build: auto-deploy"
